### PR TITLE
Fixes for localization and translation

### PR DESCRIPTION
**Pull request by milovanderlinden**
I have added various translation strings. I also changed the language in the html header to match the locale that is set.

Can you please evaluate?

Thanks!

Milo

### CODE REVIEW

**Comment by inghamn** [comment]
Seeing the the fields added to the .po file reminds me to point out the GIS Address Service integration.

Neighborhood Association and Township are both fields that are not defined in uReport.  They are injected by the AddressService as additional fields from our GIS system.

At some point, you will probably want to implement an AddressService integration for Eindhoven.

**Comment by milovanderlinden** [comment]
Eindhoven has no addressService, but there is a national service in the Netherlands that uses the OpenLS standard. There is also nominatim and the mapquest geocoder which are pretty good as a first attempt.

I think I should be able to duplicate AddressService.php and create a corresponding nominatimService.php and mapquestService.php

**Comment by inghamn** [comment]
I just want to be clear....

The AddressService is used to validate addresses.  It is not the geocoder.

In the US, the city is responsible for naming streets and issuing addresses to properties in the city.  Having  a valid address is useful for the city to dispatch someone to fix a problem.  

If a problem is reported with the water at
403 S Teeter

and it turns out that address does not exist, which door does the city knock on to ask about the water?

Geocoding is still useful, and is used for many types of reports.  However, the AddressService is for confirming that an address actually exists in the city.

**Comment by milovanderlinden** [comment]
That is clear and I misunderstood, you are correct there. We have a national open address database with services, I do not know if our city also validates, but your point is valid. I will check with the officials monday. Thanks for bringing this to attention!

**Pull request merged**
